# Imports

In [1]:
import pandas as pd
import os

In [2]:
df_miss=pd.read_csv('../data/data_miss_2011_2024.csv')

In [3]:
df_miss

,Région,Nom,Âge,Taille,Résidence,Date élection,Classement Final,année,Top 15/12,Points_du_public,Points_du_jury,Points_totaux,top_5,Classement,ID_REGION
0,Miss Alsace,Mathilde Buecher,19,1.78,Heimersdorf,2010-10-10 00:00:00.000000000,NaN,2011,False,0,0,0,False,NaN,1
1,Miss Aquitaine,Clémence Thill,20,1.75,Agen,2010-10-16 00:00:00.000000000,NaN,2011,False,0,0,0,False,NaN,2
2,Miss Auvergne,Clémence Oleksy,19,1.76,Vichy,2010-10-17 00:00:00.000000000,2e dauphine,2011,True,10,12,22,True,3.0,3
3,Miss Bourgogne,Alice Detollenaere,23,1.74,Chitry-les-Mines,2017-09-29 00:00:00.000000000,Prix du Mannequinat,2011,False,0,0,0,False,NaN,4
4,Miss Bretagne,Laury Thilleman,19,1.78,Brest,2010-10-26 00:00:00.000000000,Miss France 2011\nPrix de la Culture générale,2011,True,12,11,23,True,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Miss Provence,Adélina Blanc,25,1.73,Eyragues,2023-07-27 00:00:00.000000000,2e dauphine,2024,True,12,11,23,True,3.0,28
430,Miss Réunion,Mélanie Odules,20,1.78,Saint-Paul,2023-08-26 00:00:00.000000000,NaN,2024,False,0,0,0,False,NaN,29
431,Miss Rhône-Alpes,Alizée Bidaut,22,1.74,Saint-Genis-sur-Menthon,2023-09-23 00:00:00.000000000,NaN,2024,False,0,0,0,False,NaN,30
432,Miss Roussillon,Élise Aquilina,21,1.71,Cabestany,2023-08-05 00:00:00.000000000,Top 15 (11e)\nPrix de l’académie des Miss[25],2024,True,6,6,12,False,NaN,31
433,Miss Tahiti,Ravahere Silloux,25,1.72,Papeete,2023-06-23 00:00:00.000000000,Top 15 (6e dauphine),2024,True,8,8,16,False,NaN,33

# Couverture magasine

In [4]:
# Ajouter des colonnes pour les nouvelles données
df_miss['Couverture_TeleMagazine'] = False
df_miss['Couverture_TeleLoisirs'] = False

print("Colonnes ajoutées pour les nouvelles informations.")

Colonnes ajoutées pour les nouvelles informations.

## Liste des informations sur TéléMagazine

In [5]:
telemagazine_covers = {
    2024: ['Miss Île-de-France', 'Miss Guadeloupe', 'Miss Normandie', "Miss Côte d'Azur"],
    2023: ['Miss Guadeloupe', "Miss Côte d'Azur", 'Miss Nord-Pas-de-Calais', 'Miss Picardie'],
    2022: ['Miss Île-de-France', "Miss Côte d'Azur", 'Miss Alsace', 'Miss Rhône-Alpes'],
    2021: ['Miss Provence', 'Miss Languedoc-Roussillon', "Miss Côte d'Azur", 'Miss Normandie'],
    2020: ['Miss Provence', 'Miss Bourgogne', 'Miss Martinique'],
    2019: ['Miss Franche-Comté', 'Miss Languedoc-Roussillon', 'Miss Tahiti'],
    2018: ['Miss Nord-Pas-de-Calais', 'Miss Île-de-France', 'Miss Réunion'],
    2017: ['Miss Tahiti', 'Miss Normandie', 'Miss Guyane'],
    2016: ['Miss Réunion', 'Miss Provence', 'Miss Martinique'],
    2015: ["Miss Côte d'Azur", 'Miss Nord-Pas-de-Calais', 'Miss Haute-Savoie'],
    2014: ['Miss Orléanais', 'Miss Tahiti', 'Miss Auvergne'],
    2013: ['Miss Tahiti', 'Miss Bourgogne', 'Miss Languedoc', 'Miss Nouvelle-Calédonie'],
    2012: ['Miss Franche-Comté', 'Miss Tahiti', 'Miss Rhône-Alpes'],
    2011: []
}

In [6]:
for year, regions in telemagazine_covers.items():
    df_miss.loc[(df_miss['Région'].isin(regions)) & (df_miss['année'] == year), 'Couverture_TeleMagazine'] = True

df_miss['Couverture_TeleMagazine'] = df_miss['Couverture_TeleMagazine'].fillna(False)

print(df_miss[['Région', 'année', 'Couverture_TeleMagazine']].dropna().head(100))

                                   Région  année  Couverture_TeleMagazine
0                             Miss Alsace   2011                    False
1                          Miss Aquitaine   2011                    False
2                           Miss Auvergne   2011                    False
3                          Miss Bourgogne   2011                    False
4                           Miss Bretagne   2011                    False
..                                    ...    ...                      ...
95                       Miss Rhône-Alpes   2013                    False
96                        Miss Roussillon   2013                    False
97  Miss Saint-Martin et Saint-Barthélemy   2013                    False
98                            Miss Tahiti   2013                     True
99                            Miss Alsace   2014                    False

[100 rows x 3 columns]

## Couverture Téléloisir

In [7]:
df_miss['Couverture_Téléloisir'] = False

teleloisir_2024 = [
    'Miss Nord-Pas-de-Calais', 'Miss Alsace', 'Miss Bourgogne',
    'Miss Pays de la Loire', 'Miss Languedoc-Roussillon', 'Miss Guadeloupe'
]

df_miss.loc[
    (df_miss['Région'].isin(teleloisir_2024)) & (df_miss['année'] == 2024),
    'Couverture_Téléloisir'
] = True

In [8]:
df_miss_2024 = df_miss[df_miss['année'] == 2024][['Région', 'année', 'Couverture_Téléloisir']]
print(df_miss_2024)

                        Région  année  Couverture_Téléloisir
404                Miss Alsace   2024                   True
405             Miss Aquitaine   2024                  False
406              Miss Auvergne   2024                  False
407             Miss Bourgogne   2024                   True
408              Miss Bretagne   2024                  False
409   Miss Centre-Val-de-Loire   2024                  False
410     Miss Champagne-Ardenne   2024                  False
411                 Miss Corse   2024                  False
412           Miss Côte d'Azur   2024                  False
413         Miss Franche-Comté   2024                  False
414            Miss Guadeloupe   2024                   True
415                Miss Guyane   2024                  False
416         Miss Île-de-France   2024                  False
417  Miss Languedoc-Roussillon   2024                   True
418              Miss Limousin   2024                  False
419              Miss Lorraine   2024                  False
420            Miss Martinique   2024                  False
421               Miss Mayotte   2024                  False
422         Miss Midi-Pyrénées   2024                  False
423    Miss Nord-Pas-de-Calais   2024                   True
424             Miss Normandie   2024                  False
425    Miss Nouvelle-Calédonie   2024                  False
426      Miss Pays de la Loire   2024                   True
427              Miss Picardie   2024                  False
428      Miss Poitou-Charentes   2024                  False
429              Miss Provence   2024                  False
430               Miss Réunion   2024                  False
431           Miss Rhône-Alpes   2024                  False
432            Miss Roussillon   2024                  False
433                Miss Tahiti   2024                  False

In [9]:
df_miss

,Région,Nom,Âge,Taille,Résidence,Date élection,Classement Final,année,Top 15/12,Points_du_public,Points_du_jury,Points_totaux,top_5,Classement,ID_REGION,Couverture_TeleMagazine,Couverture_TeleLoisirs,Couverture_Téléloisir
0,Miss Alsace,Mathilde Buecher,19,1.78,Heimersdorf,2010-10-10 00:00:00.000000000,NaN,2011,False,0,0,0,False,NaN,1,False,False,False
1,Miss Aquitaine,Clémence Thill,20,1.75,Agen,2010-10-16 00:00:00.000000000,NaN,2011,False,0,0,0,False,NaN,2,False,False,False
2,Miss Auvergne,Clémence Oleksy,19,1.76,Vichy,2010-10-17 00:00:00.000000000,2e dauphine,2011,True,10,12,22,True,3.0,3,False,False,False
3,Miss Bourgogne,Alice Detollenaere,23,1.74,Chitry-les-Mines,2017-09-29 00:00:00.000000000,Prix du Mannequinat,2011,False,0,0,0,False,NaN,4,False,False,False
4,Miss Bretagne,Laury Thilleman,19,1.78,Brest,2010-10-26 00:00:00.000000000,Miss France 2011\nPrix de la Culture générale,2011,True,12,11,23,True,1.0,5,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Miss Provence,Adélina Blanc,25,1.73,Eyragues,2023-07-27 00:00:00.000000000,2e dauphine,2024,True,12,11,23,True,3.0,28,False,False,False
430,Miss Réunion,Mélanie Odules,20,1.78,Saint-Paul,2023-08-26 00:00:00.000000000,NaN,2024,False,0,0,0,False,NaN,29,False,False,False
431,Miss Rhône-Alpes,Alizée Bidaut,22,1.74,Saint-Genis-sur-Menthon,2023-09-23 00:00:00.000000000,NaN,2024,False,0,0,0,False,NaN,30,False,False,False
432,Miss Roussillon,Élise Aquilina,21,1.71,Cabestany,2023-08-05 00:00:00.000000000,Top 15 (11e)\nPrix de l’académie des Miss[25],2024,True,6,6,12,False,NaN,31,False,False,False
433,Miss Tahiti,Ravahere Silloux,25,1.72,Papeete,2023-06-23 00:00:00.000000000,Top 15 (6e dauphine),2024,True,8,8,16,False,NaN,33,False,False,False

In [10]:
dict_cult_g = {
    '2024': {
        '1': {'Candidate': 'Miss Alsace', 'Score': 14.2, 'Rank': 1},
        '2': {'Candidate': 'Miss Limousin', 'Score': 13.3, 'Rank': 2},
        '3': {'Candidate': 'Miss Roussillon', 'Score': 13.3, 'Rank': 2},
        '4': {'Candidate': 'Miss Champagne-Ardenne', 'Score': 12.3, 'Rank': 4}
    },
    '2023': {
        '1': {'Candidate': 'Miss Île-de-France', 'Score': 18.0, 'Rank': 1},
        '2': {'Candidate': 'Miss Nord-Pas-de-Calais', 'Score': 17.0, 'Rank': 2},
        '3': {'Candidate': 'Miss Guadeloupe', 'Score': 16.5, 'Rank': 3}
    },
    '2022': {
        '1': {'Candidate': 'Miss Normandie', 'Score': 17.0, 'Rank': 1},
        '2': {'Candidate': 'Miss Aquitaine', 'Score': 15.5, 'Rank': 2},
        '3': {'Candidate': 'Miss Pays de la Loire', 'Score': 15.0, 'Rank': 3}
    },
    '2021': {
        '1': {'Candidate': 'Miss Bourgogne', 'Score': 17.5, 'Rank': 1}
    },
    '2020': {
        '1': {'Candidate': 'Miss Guadeloupe', 'Score': 17.5, 'Rank': 1}
    },
    '2019': {
        '1': {'Candidate': 'Miss Centre-Val-de-Loire', 'Score': 18.5, 'Rank': 1},
        '2': {'Candidate': 'Miss Limousin', 'Score': 18.3, 'Rank': 2},
        '3': {'Candidate': 'Miss Midi-Pyrénées', 'Score': 18.0, 'Rank': 3}
    },
    '2018': {
        '1': {'Candidate': 'Miss Corse', 'Score': 18.0, 'Rank': 1}
    },
    '2017': {
        '1': {'Candidate': 'Miss Île-de-France', 'Score': 17.0, 'Rank': 1}
    },
    '2016': {
        '1': {'Candidate': 'Miss Nord-Pas-de-Calais', 'Score': 17.5, 'Rank': 1}
    },
    '2015': {
        '1': {'Candidate': 'Miss Île-de-France', 'Score': 19.5, 'Rank': 1}
    },
    '2014': {
        '1': {'Candidate': 'Miss Alsace', 'Score': 18.0, 'Rank': 1}
    },
    '2013': {
        '1': {'Candidate': 'Miss Bourgogne', 'Score': 17.0, 'Rank': 1}
    },
    '2013': {
        '1': {'Candidate': 'Miss Côte d\'Azur', 'Score': 0.0, 'Rank': 1}
    }
}

In [12]:
df_miss['Score_Culture_G'] = 0.0
df_miss['Rank_Culture_G'] = 30
df_miss['Top_Culture_G'] = False

for year, candidates in dict_cult_g.items():
    for _, data in candidates.items():
        candidate_name = data['Candidate']
        score = data['Score']
        rank = data['Rank']
        
        condition = (df_miss['Région'] == candidate_name) & (df_miss['année'] == int(year))
        
        if condition.any():
            df_miss.loc[condition, 'Score_Culture_G'] = score
            df_miss.loc[condition, 'Rank_Culture_G'] = rank
            df_miss.loc[condition, 'Top_Culture_G'] = True

print(df_miss[['Région', 'année', 'Score_Culture_G', 'Rank_Culture_G', 'Top_Culture_G']].dropna())

               Région  année  Score_Culture_G  Rank_Culture_G  Top_Culture_G
0         Miss Alsace   2011              0.0              30          False
1      Miss Aquitaine   2011              0.0              30          False
2       Miss Auvergne   2011              0.0              30          False
3      Miss Bourgogne   2011              0.0              30          False
4       Miss Bretagne   2011              0.0              30          False
..                ...    ...              ...             ...            ...
429     Miss Provence   2024              0.0              30          False
430      Miss Réunion   2024              0.0              30          False
431  Miss Rhône-Alpes   2024              0.0              30          False
432   Miss Roussillon   2024             13.3               2           True
433       Miss Tahiti   2024              0.0              30          False

[434 rows x 5 columns]

# Suivi sur insta

In [18]:
followers_instagram = {
    2024: {
        "Miss Côte d'Azur": 100000,
        "Miss Île-de-France": 91500,
        "Miss Guadeloupe": 57500,
        "Miss Guyane": 34500,
        "Miss Alsace": 24500,
        "Miss Languedoc-Roussillon": 22300,
        "Miss Normandie": 20300,
        "Miss Réunion": 18300,
        "Miss Nord-Pas-de-Calais": 18200,
        "Miss Provence": 15300,
        "Miss Champagne-Ardenne": 14500,
        "Miss Pays de la Loire": 13500,
        "Miss Rhône-Alpes": 13000,
        "Miss Tahiti": 13400,
        "Miss Centre-Val-de-Loire": 11900,
    },
    2023: {
        "Miss Réunion": 40400,
        "Miss Nord-Pas-de-Calais": 38800,
        "Miss Guadeloupe": 32900,
        "Miss Midi-Pyrénées": 31000,
        "Miss Côte d'Azur": 25200,
        "Miss Franche-Comté": 22400,
        "Miss Languedoc-Roussillon": 16800,
        "Miss Normandie": 16300,
        "Miss Lorraine": 15200,
        "Miss Pays de la Loire": 12900,
        "Miss Provence": 12600,
        "Miss Rhône-Alpes": 11100,
        "Miss Champagne-Ardenne": 10500,
        "Miss Auvergne": 10300,
        "Miss Roussillon": 9463,
        "Miss Guyane": 7000,
    },
    2022: {
        "Miss Alsace": 87000,
        "Miss Champagne-Ardenne": 49700,
        "Miss Provence": 39400,
        "Miss Rhône-Alpes": 33800,
        "Miss Nord-Pas-de-Calais": 33400,
        "Miss Île-de-France": 23600,
        "Miss Côte d'Azur": 22500,
        "Miss Bourgogne": 21700,
        "Miss Réunion": 20600,
        "Miss Languedoc-Roussillon": 15700,
        "Miss Tahiti": 13700,
        "Miss Normandie": 13600,
        "Miss Guadeloupe": 13300,
        "Miss Corse": 12900,
    },
    2021: {
        'Miss Côte d\'Azur': 58000,
        'Miss Bourgogne': 52000,
        'Miss Provence': 40000,
        'Miss Nord-Pas-de-Calais': 15000,
    },
    2020: {
        'Miss Provence': 213982,
        'Miss Nord-Pas-de-Calais': 46787,
        'Miss Côte d\'Azur': 42424,
        'Miss Normandie': 17857,
        'Miss Pays de la Loire': 16800,
    },
    2019: {
        'Miss Tahiti': 30062,
        'Miss Réunion': 27201,
        'Miss Normandie': 26128,
        'Miss Languedoc-Roussillon': 25014,
        'Miss Guadeloupe': 13800
    }
}

In [21]:
# Ajouter une colonne pour chaque année disponible dans le dictionnaire
for year, data in followers_instagram.items():
    column_name = f"Instagram_Followers_{year}"
    df_miss[column_name] = df_miss.apply(
        lambda row: data.get(row['Région'], 0) if row['année'] == year else 0, axis=1
    )

# Vérification des données pour 2022
df_miss_2022 = df_miss[df_miss['année'] == 2022]
print(df_miss_2022[['Région', 'année', 'Instagram_Followers_2022']])

                        Région  année  Instagram_Followers_2022
345                Miss Alsace   2022                     87000
346             Miss Aquitaine   2022                         0
347              Miss Auvergne   2022                         0
348             Miss Bourgogne   2022                     21700
349              Miss Bretagne   2022                         0
350   Miss Centre-Val-de-Loire   2022                         0
351     Miss Champagne-Ardenne   2022                     49700
352                 Miss Corse   2022                     12900
353           Miss Côte d'Azur   2022                     22500
354         Miss Franche-Comté   2022                         0
355            Miss Guadeloupe   2022                     13300
356                Miss Guyane   2022                         0
357         Miss Île-de-France   2022                     23600
358  Miss Languedoc-Roussillon   2022                     15700
359              Miss Limousin   2022                         0
360              Miss Lorraine   2022                         0
361            Miss Martinique   2022                         0
362               Miss Mayotte   2022                         0
363         Miss Midi-Pyrénées   2022                         0
364    Miss Nord-Pas-de-Calais   2022                     33400
365             Miss Normandie   2022                     13600
366    Miss Nouvelle-Calédonie   2022                         0
367      Miss Pays de la Loire   2022                         0
368              Miss Picardie   2022                         0
369      Miss Poitou-Charentes   2022                         0
370              Miss Provence   2022                     39400
371               Miss Réunion   2022                     20600
372           Miss Rhône-Alpes   2022                     33800
373                Miss Tahiti   2022                     13700